### ISSUE TITLE
I think this separate repo is not necessary

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan-debian#1]
I just stumbled across this.  I think this separate repo can be closed once I have incorporated your changes.  The debian packaging should ideally be a separate branch in the main repo.

**Comment by ereOn** [comment]
@leggewie I would indeed like that better. Fine by me !

I no issue with deleting this repository once the work on the official repository is done.

**Comment by leggewie** [comment]
let's delete it, then
